CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(72) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  address_1 VARCHAR(100) NOT NULL,
  address_2 VARCHAR(100),
  city VARCHAR(50) NOT NULL,
  state VARCHAR(2) NOT NULL,
  zip_code VARCHAR(5) NOT NULL,
  phone_number VARCHAR(11),
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_deleted TIMESTAMP
);